name: Deploy Fake
on:
    workflow_call:
jobs:
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.ambiente }}"
            - name: Curl Deploy no ambiente
              run: "curl -X POST https://webhook.site/e45ac201-9b23-4044-961c-3e174cc28ffa -d '{ambiente: ${{ secrets.ambiente }}}'"